


const languages = {
    en: {
        welcome: "Welcome back!",
        signIn: "Sign in to your e-commerce account",
        username: "Username",
        password: "Password",
        forgotPassword: "Forgot your password?",
        signInButton: "Sign in",
        noAccount: "Don't have an account?",
        register: "Register here",
        title: "Create your account",
        rePassword: "Re-enter Password",
        avatar: "Avatar",
        upload: "Upload",
        role: "Role",
        selectRole: "Select a role",
        user: "User",
        admin: "Admin",
        manager: "Manager",
        firstName: "First name",
        lastName: "Last name",
        address: "Address",
        phone: "Phone",
        email: "Email",
        personalId: "Personal ID",
        provinceCode: "Province Code",
        districtCode: "District Code",
        wardCode: "Ward Code",
        registering: "Registering...",
        companyName: "Company Name",
        help: "Help",
        faq: "FAQ",
        customerSupport: "Customer Support",
        contactUs: "Contact Us",
        resources: "Resources",
        blog: "Blog",
        whitepapers: "Whitepapers",
        caseStudies: "Case Studies",
        extraLinks: "Extra Links",
        aboutUs: "About Us",
        careers: "Careers",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service"
    },
    vi: {
        welcome: "Chào mừng trở lại!",
        signIn: "Đăng nhập vào tài khoản thương mại điện tử của bạn",
        username: "Tên đăng nhập",
        password: "Mật khẩu",
        forgotPassword: "Quên mật khẩu?",
        signInButton: "Đăng nhập",
        noAccount: "Chưa có tài khoản?",
        register: "Đăng ký tại đây",
        title: "Tạo tài khoản của bạn",
        rePassword: "Nhập lại mật khẩu",
        avatar: "Ảnh đại diện",
        upload: "Tải lên",
        role: "Vai trò",
        selectRole: "Chọn vai trò",
        user: "Người dùng",
        admin: "Quản trị viên",
        manager: "Quản lý",
        firstName: "Tên",
        lastName: "Họ",
        address: "Địa chỉ",
        phone: "Số điện thoại",
        email: "Email",
        personalId: "CMND/CCCD",
        provinceCode: "Mã tỉnh",
        districtCode: "Mã huyện",
        wardCode: "Mã xã",
        registering: "Đang đăng ký...",
        companyName: "Tên Công Ty",
        help: "Trợ Giúp",
        faq: "Câu Hỏi Thường Gặp",
        customerSupport: "Hỗ Trợ Khách Hàng",
        contactUs: "Liên Hệ Với Chúng Tôi",
        resources: "Tài Nguyên",
        blog: "Blog",
        whitepapers: "Tài Liệu Trắng",
        caseStudies: "Nghiên Cứu Tình Huống",
        extraLinks: "Liên Kết Bổ Sung",
        aboutUs: "Về Chúng Tôi",
        careers: "Sự Nghiệp",
        privacyPolicy: "Chính Sách Bảo Mật",
        termsOfService: "Điều Khoản Dịch Vụ"
    }
};

export default languages;